apiVersion: v1
kind: Pod
metadata:
  name: ubuntuapp-custom1
  labels:
    app: ubuntuapp-custom1
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "qa", "name":"custom1-vn"}'
  }
spec:
  containers:
    - name: ubuntuapp-custom1
      image: ubuntu-upstart
