apiVersion: v1
kind: Pod
metadata:
  name: ubuntuapp-custom2
  labels:
    app: ubuntuapp-custom2
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "qa", "name":"custom2-vn"}'
  }
spec:
  containers:
    - name: ubuntuapp-custom2
      image: ubuntu-upstart
