apiVersion: v1
kind: Pod
metadata:
  name: custom-app
  labels:
    app: custom-app
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "default", "name":"disney-cust-vn"}'
  }
spec:
  containers:
    - name: custom-app
      image: nginx
